<a href="https://colab.research.google.com/github/Lord-Matthew/Linear-Algebra-58020/blob/main/Determinant_of_a_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]]) #Preparing the array
A1 = np.linalg.det(A) #Command needed to find the determinant of the given array
print(A)
print(A1)
print(round(A1)) #Rounded form of the answer 

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-13.999999999999996
-14
