<a href="https://colab.research.google.com/github/Lord-Matthew/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Final Exam

In [1]:
import numpy as np
from numpy.linalg import eig

##Problem 1 

##Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? 

In [12]:
Stu1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
Stu2 = np.array([[89],[89],[95]])

T = np.linalg.inv(Stu1).dot(Stu2)
print(T)

[[13.]
 [57.]
 [19.]]


##Problem 2

##Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

##Answer
The matrix is singular, we cannot somehow inverse it but we can use pinv to see the output and the results.

##Problem 3 Consider the matrix, (40 points)

1. Find the eigenvalue/s
2. Find the eigenvectors


In [8]:
z=np.array ([[8,5,-6],[-12,-9,-12],[-3,-3,5]]) #Create an array from the given
print(z)

b,c= np.linalg.eig(z)   #This syntax shows how to find the eigenvalues and vectors
print ("The eigenvalue/s is/are:",b)

[[  8   5  -6]
 [-12  -9 -12]
 [ -3  -3   5]]
The eigenvalue/s is/are: [-8.11684397  3.          9.11684397]


In [9]:
print ("The eigenvectors are:",c)

The eigenvectors are: [[ 2.35632155e-01 -7.07106781e-01 -8.61671223e-01]
 [-9.57707415e-01  7.07106781e-01  2.99299241e-01]
 [-1.65148399e-01 -1.19155502e-16  4.09808086e-01]]
