<a href="https://colab.research.google.com/github/Lord-Matthew/Linear-Algebra-58020/blob/main/Matrix_Transpose_and_Inverse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
##Create 3x3 or 4x4 matrix and apply Transpose
import numpy as np
A=np.array([[6,8,7],[5,4,6],[3,1,1]])
print(A)
B=np.transpose(A)
print(B)

[[6 8 7]
 [5 4 6]
 [3 1 1]]
[[6 5 3]
 [8 4 1]
 [7 6 1]]


In [12]:
##Create 3x3 or 4x4 matrix and apply Inverse
C=np.linalg.inv(A)
print(C)
D=np.dot(A,C)
print(D)

[[-0.04651163 -0.02325581  0.46511628]
 [ 0.30232558 -0.34883721 -0.02325581]
 [-0.1627907   0.41860465 -0.37209302]]
[[ 1.00000000e+00 -2.22044605e-16  1.66533454e-16]
 [-2.22044605e-16  1.00000000e+00  3.33066907e-16]
 [-5.55111512e-17 -2.77555756e-16  1.00000000e+00]]
