<a href="https://colab.research.google.com/github/Lord-Matthew/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##Question Number 1

In [2]:
A = np.eye(5) #this is the syntax that will display its identity with a length of 5
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##Question Number 2


In [4]:
B = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]]) #in this you will show that the elements below the principal diagonal is zero
print(B)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


##Question Number 3

In [9]:
C = np.array([[1,2,6],[2,8,4],[6,4,5]])
print(C)

[[1 2 6]
 [2 8 4]
 [6 4 5]]


##Question Number 4

In [6]:
D = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #create an array with the given numbers and convert it into a matrix
print(D)
E = np.linalg.inv(D) #this syntax shows that the given matrix will be inversed
print(E)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##Question Number 5

In [7]:
D = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #create an array with the given numbers and convert it into a matrix
print(D)
print(np.linalg.det(D)) #this syntax will compute the determinant of an array
print(round(np.linalg.det(D))) #this syntax will round off the determinant into a whole number

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


##Question Number 6

In [8]:
D = np.array([[5,4,1,3.4],[10,9,4,8.8],[10,13,15,19.2]]) #Create an array based on the given
print(D)

sqrtD = np.sqrt(D) # this line contains the command to find the roots of the given matrix
print(" ")
print("Roots:")
print(" ")
print(sqrtD)

[[ 5.   4.   1.   3.4]
 [10.   9.   4.   8.8]
 [10.  13.  15.  19.2]]
 
Roots:
 
[[2.23606798 2.         1.         1.84390889]
 [3.16227766 3.         2.         2.96647939]
 [3.16227766 3.60555128 3.87298335 4.38178046]]
