<a href="https://colab.research.google.com/github/Lord-Matthew/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PRACTICAL LAB EXAM 1

In [25]:
import numpy as np

# PROBLEM 1

In [24]:
w = np.array([[1,-3,0],[2,-2,0],[3,1,0]])
x = np.array([[3,2,1],[-1,2,32],[2,1,-1]])
y = np.array([[1,2,0],[0,-1,2],[0,0,0]])
z = np.array([[0,1],[2,3]])

# LETTER A

In [26]:
output=np.dot(w,y)
print(output)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


# LETTER B

In [27]:
output=np.add(z,z)
print(output)

[[0 2]
 [4 6]]


# LETTER C

In [28]:
output=np.dot(3,x)
print(output)

[[ 9  6  3]
 [-3  6 96]
 [ 6  3 -3]]


# PROBLEM 2

#The product (YW)2 is not defined

In [29]:
prob=np.cross(y,w)
ans=2*prob
print(ans)

[[  0   0 -10]
 [  8   8   4]
 [  0   0   0]]


#WY – X

In [34]:
bpb=np.dot(w,y)
bp2=np.subtract(bpb,w)
print(bp2)

[[ 0  8 -6]
 [ 0  8 -4]
 [ 0  4  2]]


#YW – Z^2

In [42]:
cpb=np.dot(y,w)
cpb2=2*z

cpb=([[5,-7],[4,4]])

cpb3=np.subtract(cpb,cpb2)
print(cpb3)

[[ 5 -9]
 [ 0 -2]]
