<a href="https://colab.research.google.com/github/Lord-Matthew/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [ ]:
import numpy as np

In [ ]:
#Addition of Matrices
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A+B)

[[ 1 -3]
 [ 6  4]]


In [ ]:
#Difference of Matrices (A-B)
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A-B)

[[-11   3]
 [  2  -2]]


In [ ]:
#Difference of Matrices (B-B)
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(B-B)

[[0 0]
 [0 0]]
