<a href="https://colab.research.google.com/github/Lord-Matthew/Linear-Algebra-58020/blob/main/Vector_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operations

In [ ]:
import numpy as np
#Create a 1 x 3 array
a = np.array([1,3,-5])
print(a)

[ 1  3 -5]


In [ ]:
#Create a 2 x 3 array
b = np.array([[1,4,-3],[4,-3,5]]) #Example of rectangular array
print(b)

[[ 1  4 -3]
 [ 4 -3  5]]


In [ ]:
#Create a 3 x 3 matrix
c = np.array([[1,4,-3],[5,-3,4],[6,-5,2]])
print(c)

[[ 1  4 -3]
 [ 5 -3  4]
 [ 6 -5  2]]


In [ ]:
#Create a constant array with all values are 6
d = np.full((4,4),6) #Example of square matrix
print(d)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
#Create a diagonal matrix
e = np.array([[1,4,-3],[5,-3,4],[6,-5,2]])
print(e)
e = np.diagonal([[1,4,-3],[5,-3,4],[6,-5,2]])
print(e)

[[ 1  4 -3]
 [ 5 -3  4]
 [ 6 -5  2]]
[ 1 -3  2]


In [ ]:
#Create an identity matrix
f = np.eye(6)
print(f)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
#Create a zero matrix
f = np.zeros((4,4))
print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Create an empty matrix
h = np.empty((0,5))
print(h)

[]


In [ ]:
#Addition of Matrices
i = np.array([[1,4,-3],[5,-3,4]])
j = np.array([[4,-5,3],[3,6,9]])
print(i+j)

[[ 5 -1  0]
 [ 8  3 13]]


In [ ]:
#Subtraction of Matrices
i = np.array([[1,4,-3],[5,-3,4]])
j = np.array([[4,-5,3],[3,6,9]])
print(i-j)

[[-3  9 -6]
 [ 2 -9 -5]]
